import type {
  PlatformApplication,
  PlatformAsset,
  PlatformAuditEvent,
  PlatformJob,
  PlatformProject,
  PlatformRole,
  PlatformUser,
} from './types';

export const PLATFORM_PROJECTS: PlatformProject[] = [
  {
    assetCount: 48,
    code: 'CR-2026-017',
    description: '面向城际线路的轻量化客室概念方案与材料验证。',
    id: 'project-urban-01',
    members: 8,
    name: '城际列车客室概念方案',
    stage: 'design',
    updatedAt: '今天 10:24',
  },
  {
    assetCount: 31,
    code: 'CR-2026-011',
    description: '卧铺区域空间组织、照明及软装材料的方案深化。',
    id: 'project-sleeper-02',
    members: 5,
    name: '智能卧铺客室升级',
    stage: 'concept',
    updatedAt: '昨天 17:40',
  },
  {
    assetCount: 76,
    code: 'CR-2025-086',
    description: '既有动车组一等座区域更新及交付资料归档。',
    id: 'project-firstclass-03',
    members: 12,
    name: '一等座区域焕新',
    stage: 'delivery',
    updatedAt: '07月30日',
  },
];

export const PLATFORM_ASSETS: PlatformAsset[] = [
  {
    accent: '#d8d1c5',
    createdAt: '今天 10:18',
    description: '用于客室整体效果生成的空间参考图。',
    favorite: true,
    format: 'PNG',
    id: 'asset-cabin-reference',
    name: '客室空间参考图 A',
    owner: '张晨',
    projectId: 'project-urban-01',
    size: '4.8 MB',
    source: 'upload',
    tags: ['客室', '参考图'],
    type: 'image',
    version: 3,
  },
  {
    accent: '#7a8793',
    createdAt: '今天 09:46',
    description: '座椅与侧墙区域的局部重绘遮罩。',
    favorite: false,
    format: 'PNG',
    id: 'asset-seat-mask',
    name: '座椅区域遮罩',
    owner: '李隽',
    projectId: 'project-urban-01',
    size: '1.2 MB',
    source: 'upload',
    tags: ['遮罩', '座椅'],
    type: 'image',
    version: 1,
  },
  {
    accent: '#b99976',
    createdAt: '昨天 18:05',
    description: '暖灰织物、拉丝金属与低饱和地板组合。',
    favorite: true,
    format: 'ZIP',
    id: 'asset-cmf-warm',
    name: '暖灰 CMF 材质组',
    owner: '张晨',
    projectId: 'project-urban-01',
    size: '18.6 MB',
    source: 'workflow',
    sourceAppKey: 'cmf-generator',
    tags: ['CMF', '暖灰'],
    type: 'archive',
    version: 2,
  },
  {
    accent: '#ba1f33',
    createdAt: '07月31日 15:20',
    description: '城际车型现代简约风格 LoRA，待发布。',
    favorite: false,
    format: 'SAFETENSORS',
    id: 'asset-lora-urban',
    name: '城际客室风格 LoRA',
    owner: '王璐',
    projectId: 'project-urban-01',
    size: '172 MB',
    source: 'workflow',
    sourceAppKey: 'lora-training',
    tags: ['LoRA', '现代简约'],
    type: 'model',
    version: 4,
  },
  {
    accent: '#315b70',
    createdAt: '07月30日 11:32',
    description: '方案评审用阶段性材料汇总。',
    favorite: true,
    format: 'PPTX',
    id: 'asset-review-report',
    name: '客室方案阶段评审报告',
    owner: '陈默',
    projectId: 'project-urban-01',
    size: '28.4 MB',
    source: 'workflow',
    sourceAppKey: 'report-generator',
    tags: ['报告', '评审'],
    type: 'document',
    version: 5,
  },
  {
    accent: '#c9b9a6',
    createdAt: '昨天 16:48',
    description: '卧铺包间的暖色氛围参考。',
    favorite: false,
    format: 'JPG',
    id: 'asset-sleeper-reference',
    name: '卧铺包间氛围参考',
    owner: '周昕',
    projectId: 'project-sleeper-02',
    size: '6.1 MB',
    source: 'upload',
    tags: ['卧铺', '氛围'],
    type: 'image',
    version: 1,
  },
];

export const PLATFORM_APPLICATIONS: PlatformApplication[] = [
  {
    acceptedAssetTypes: ['image', 'model'],
    category: 'generation',
    color: '#b91c32',
    description: '根据平面、参考图与设计约束生成客室整体效果方案。',
    icon: 'lucide:train-front',
    key: 'cabin-generator',
    name: '客室效果生成',
    outputAssetTypes: ['image'],
    provider: '待配置服务',
    shortName: '客室',
    status: 'testing',
    updatedAt: '今天 09:30',
  },
  {
    acceptedAssetTypes: ['image', 'archive'],
    category: 'design',
    color: '#9b6b43',
    description: '形成可复用的色彩、材料与表面纹理组合。',
    icon: 'lucide:swatch-book',
    key: 'cmf-generator',
    name: 'CMF 方案生成',
    outputAssetTypes: ['image', 'archive'],
    provider: '待配置服务',
    shortName: 'CMF',
    status: 'testing',
    updatedAt: '昨天 17:20',
  },
  {
    acceptedAssetTypes: ['image'],
    category: 'generation',
    color: '#315b70',
    description: '生成座椅、桌板、行李架等零部件多角度方案。',
    icon: 'lucide:boxes',
    key: 'part-generator',
    name: '零部件生成',
    outputAssetTypes: ['image'],
    provider: '待配置服务',
    shortName: '部件',
    status: 'testing',
    updatedAt: '07月31日',
  },
  {
    acceptedAssetTypes: ['image'],
    category: 'training',
    color: '#62558b',
    description: '管理训练数据集、训练参数、模型版本与发布状态。',
    icon: 'lucide:brain-circuit',
    key: 'lora-training',
    name: 'LoRA 训练',
    outputAssetTypes: ['model'],
    provider: '待配置服务',
    shortName: 'LoRA',
    status: 'planned',
    updatedAt: '07月30日',
  },
  {
    acceptedAssetTypes: ['image'],
    category: 'generation',
    color: '#3f6b5a',
    description: '基于正视、侧视和俯视输入生成三维模型资产。',
    icon: 'lucide:box',
    key: 'model3d-generator',
    name: '2D 生 3D',
    outputAssetTypes: ['model3d'],
    provider: '待配置服务',
    shortName: '3D',
    status: 'planned',
    updatedAt: '07月29日',
  },
  {
    acceptedAssetTypes: ['archive', 'image', 'model3d', 'text'],
    category: 'report',
    color: '#876d37',
    description: '选取项目资产，生成结构化 Word 或 PPT 方案报告。',
    icon: 'lucide:file-chart-column',
    key: 'report-generator',
    name: '自动报告',
    outputAssetTypes: ['document'],
    provider: '待配置服务',
    shortName: '报告',
    status: 'planned',
    updatedAt: '07月28日',
  },
];

export const PLATFORM_JOBS: PlatformJob[] = [
  {
    appKey: 'cabin-generator',
    createdAt: '今天 10:06',
    duration: '02:18',
    id: 'job-20260803-001',
    inputAssetIds: ['asset-cabin-reference', 'asset-cmf-warm'],
    name: '城际客室暖灰方案生成',
    outputAssetId: 'asset-cmf-warm',
    owner: '张晨',
    progress: 100,
    projectId: 'project-urban-01',
    stage: '结果已登记为项目资产',
    status: 'succeeded',
  },
  {
    appKey: 'part-generator',
    createdAt: '今天 09:42',
    id: 'job-20260803-002',
    inputAssetIds: ['asset-seat-mask'],
    name: '座椅扶手局部方案',
    owner: '李隽',
    progress: 68,
    projectId: 'project-urban-01',
    stage: '正在生成候选结果',
    status: 'running',
  },
  {
    appKey: 'lora-training',
    createdAt: '昨天 18:20',
    id: 'job-20260802-011',
    inputAssetIds: [],
    name: '城际客室风格训练',
    owner: '王璐',
    progress: 12,
    projectId: 'project-urban-01',
    stage: '等待训练服务接入',
    status: 'queued',
  },
];

export const PLATFORM_USERS: PlatformUser[] = [
  {
    department: '工业设计中心',
    email: 'zhangchen@rail.local',
    id: 'user-001',
    lastActive: '刚刚',
    name: '张晨',
    projectCount: 3,
    roleCodes: ['admin'],
    roles: ['管理员'],
    status: 'enabled',
    username: 'vben',
  },
  {
    department: '客室设计所',
    email: 'lijun@rail.local',
    id: 'user-002',
    lastActive: '8 分钟前',
    name: '李隽',
    projectCount: 2,
    roleCodes: ['user'],
    roles: ['普通用户'],
    status: 'enabled',
    username: 'lijun',
  },
  {
    department: '数字化研发部',
    email: 'wanglu@rail.local',
    id: 'user-003',
    lastActive: '今天 09:12',
    name: '王璐',
    projectCount: 4,
    roleCodes: ['user'],
    roles: ['普通用户'],
    status: 'enabled',
    username: 'wanglu',
  },
  {
    department: '外部协作组',
    email: 'zhaoming@rail.local',
    id: 'user-004',
    lastActive: '07月29日',
    name: '赵明',
    projectCount: 1,
    roleCodes: ['user'],
    roles: ['普通用户'],
    status: 'disabled',
    username: 'zhaoming',
  },
];

export const PLATFORM_ROLES: PlatformRole[] = [
  {
    code: 'admin',
    description: '管理用户、应用、工作流发布及全部平台资源。',
    id: 'role-admin',
    name: '管理员',
    permissionCount: 28,
    scope: '全部数据',
    userCount: 2,
  },
  {
    code: 'user',
    description: '创建项目资产并使用已授权的设计应用。',
    id: 'role-designer',
    name: '普通用户',
    permissionCount: 16,
    scope: '本人及项目',
    userCount: 18,
  },
];

export const PLATFORM_AUDIT_EVENTS: PlatformAuditEvent[] = [
  {
    action: '切换项目',
    createdAt: '今天 10:24:18',
    id: 'audit-001',
    ip: '10.24.18.36',
    module: '项目',
    operator: '张晨',
    result: 'success',
    target: '城际列车客室概念方案',
  },
  {
    action: '创建资产版本',
    createdAt: '今天 10:18:42',
    id: 'audit-002',
    ip: '10.24.18.36',
    module: '资产',
    operator: '张晨',
    result: 'success',
    target: '客室空间参考图 A / V3',
  },
  {
    action: '提交任务',
    createdAt: '今天 10:06:07',
    id: 'audit-003',
    ip: '10.24.18.36',
    module: '应用',
    operator: '张晨',
    result: 'success',
    target: '客室效果生成',
  },
  {
    action: '修改用户角色',
    createdAt: '昨天 16:32:54',
    id: 'audit-004',
    ip: '10.24.7.12',
    module: '用户',
    operator: '系统管理员',
    result: 'success',
    target: '王璐 / 普通用户',
  },
];
